### PR TITLE
200 CPP/SHM: Refactor WritePriorityLock to use per-PID semaphores for resilient consumer updates

### LINKED ISSUE #200: CPP/SHM: Resilient handling of ghost processes in WritePriorityLock update notification
Currently, `WritePriorityLock` handles consumer updates using a global `consumer_count_` and a single shared semaphore (`sem_update_`). When `postUpdate()` is called, it performs `sem_post` as many times as there are registered consumers.
The issue arises when a consumer process crashes or exits unexpectedly without cleaning up. It leaves the global consumer count inflated and fails to consume its share of `sem_update_`. As a result, subsequent calls to `postUpdate()` accumulate extra tokens in the semaphore, causing remaining active consumers to read false update signals and become desynchronized.

To make the update notification resilient to ghost processes:

1. Replace the global `consumer_count_` with a shared memory array of consumer PIDs (`consumer_pids_`).
2. Assign a dedicated, process-specific semaphore for each registered consumer (e.g., `<name>_update_<PID>)`.
3. Add a cleanup mechanism in `registerConsumer()` that uses `kill(pid, 0)` to detect and remove dead processes (and unlink their orphaned semaphores).
4. Update `postUpdate()` to iterate over the array and post to each valid PID's specific semaphore. This must remain extremely fast and avoid heavy syscalls (like `kill()`) in the hot path.

### PR DESCRIPTION
**Pull request by ecourtois**
This PR completely overhauls the consumer update signaling mechanism in `WritePriorityLock` to prevent dead processes from corrupting the synchronization state of active consumers.

- **Replaced Counter with PID Array:** The shared memory `consumer_count_` integer has been swapped for a fixed-size array (`consumer_pids_`) that stores up to 32 active consumer process IDs.
- **Per-PID Semaphores:** The global `sem_update_` has been dropped. Each consumer now listens to its own specific semaphore (`/<name>_update_<PID>`).
- **Ghost Process Garbage Collection:** When `registerConsumer()` is called, it actively scans the PID array. If a registered process no longer exists (`kill(pid, 0) == -1 && errno == ESRCH`), its slot is reclaimed and its orphaned semaphore is unlinked.
- **Optimized `postUpdate()`:** `postUpdate()` now iterates over the array and posts a token to each valid consumer's semaphore. To maintain peak performance, it uses an internal `std::unordered_map` cache (`update_sems_cache_`) to store opened semaphore references instead of calling `sem_open` on every cycle.
- **Clean unregistration:** Destructors gracefully clean up the array slot and locally created semaphores upon nominal exit.

### CODE REVIEW

File: cogip/cpp/libraries/shared_memory/WritePriorityLock.cpp [hunk 1]
```diff
@@ -240,32 +247,97 @@ void WritePriorityLock::finishWriting() {
...
+            auto it = update_sems_cache_.find(pid);
+            if (it != update_sems_cache_.end()) {
+                target_sem = it->second;
+            } else {
+                std::string target_sem_name = "/" + name_ + "_update_" + std::to_string(pid);
+                target_sem = sem_open(target_sem_name.c_str(), O_RDWR);
+                if (target_sem != SEM_FAILED) {
+                    update_sems_cache_[pid] = target_sem;
+                } else {
+                    target_sem = nullptr; // could be unlinked or not created yet
```
Comment (gdoffe) [inline cogip/cpp/libraries/shared_memory/WritePriorityLock.cpp:308]: if `sem_open` fails here, that means that the process is likely dead, I would purge the pid from the array after testing `kill(pid, 0)`.
That would allow an other clean in a more frequent function, because `postUpdate` is called more often than `registerConsumer`. WDYT ?

**Review by gdoffe — CHANGES_REQUESTED** [review]

**Review by mlecriva — APPROVED** [review]
LGTM

**Review by gdoffe — APPROVED** [review]
LGTM ;)
